# Read the Docs configuration
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"

# Install API package with dev extras (includes Sphinx + autodoc deps)
python:
  install:
    - method: pip
      path: apps/api
      extra_requirements:
        - dev

# Sphinx docs live in apps/api/docs/
sphinx:
  configuration: apps/api/docs/conf.py
