"""initial schema

Revision ID: 7071adf96d33
Revises: 
Create Date: 2026-04-14 13:49:58.227392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pathfinder.persistence.models

# revision identifiers, used by Alembic.
revision: str = '7071adf96d33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', pathfinder.persistence.models.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('control_sets',
    sa.Column('id', pathfinder.persistence.models.GUID(), nullable=False),
    sa.Column('user_id', pathfinder.persistence.models.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('positive_ids', sa.JSON(), nullable=False),
    sa.Column('negative_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_control_sets_site_id', 'control_sets', ['site_id'], unique=False)
    op.create_index('ix_control_sets_user_id', 'control_sets', ['user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', pathfinder.persistence.models.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('benchmark_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiments_batch_id', 'experiments', ['batch_id'], unique=False)
    op.create_index('ix_experiments_benchmark_id', 'experiments', ['benchmark_id'], unique=False)
    op.create_index('ix_experiments_site_id', 'experiments', ['site_id'], unique=False)
    op.create_index('ix_experiments_user_id', 'experiments', ['user_id'], unique=False)
    op.create_table('gene_sets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', pathfinder.persistence.models.GUID(), nullable=True),
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gene_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('wdk_strategy_id', sa.Integer(), nullable=True),
    sa.Column('wdk_step_id', sa.Integer(), nullable=True),
    sa.Column('search_name', sa.String(length=255), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('parent_set_ids', sa.JSON(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gene_sets_site_id', 'gene_sets', ['site_id'], unique=False)
    op.create_index('ix_gene_sets_user_id', 'gene_sets', ['user_id'], unique=False)
    op.create_index('ix_gene_sets_user_site', 'gene_sets', ['user_id', 'site_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', pathfinder.persistence.models.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('wdk_strategy_id', sa.Integer(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('pipeline', sa.JSON(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('estimated_size', sa.Integer(), nullable=True),
    sa.Column('gene_set_id', sa.String(length=50), nullable=True),
    sa.Column('gene_set_auto_imported', sa.Boolean(), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gene_set_id'], ['gene_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chats_user_site', 'chats', ['user_id', 'site_id'], unique=False)
    op.create_index('ix_chats_wdk_strategy_id', 'chats', ['wdk_strategy_id'], unique=True, postgresql_where='wdk_strategy_id IS NOT NULL')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messages_chat_id_created_at_idx', 'messages', ['chat_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_chat_id_created_at_idx', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chats_wdk_strategy_id', table_name='chats', postgresql_where='wdk_strategy_id IS NOT NULL')
    op.drop_index('ix_chats_user_site', table_name='chats')
    op.drop_table('chats')
    op.drop_index('ix_gene_sets_user_site', table_name='gene_sets')
    op.drop_index('ix_gene_sets_user_id', table_name='gene_sets')
    op.drop_index('ix_gene_sets_site_id', table_name='gene_sets')
    op.drop_table('gene_sets')
    op.drop_index('ix_experiments_user_id', table_name='experiments')
    op.drop_index('ix_experiments_site_id', table_name='experiments')
    op.drop_index('ix_experiments_benchmark_id', table_name='experiments')
    op.drop_index('ix_experiments_batch_id', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_control_sets_user_id', table_name='control_sets')
    op.drop_index('ix_control_sets_site_id', table_name='control_sets')
    op.drop_table('control_sets')
    op.drop_table('users')
    # ### end Alembic commands ###
